"""
generate_notebook.py
Run this script ONCE to create research_paper_analyzer.ipynb
Usage: python generate_notebook.py
"""

import json, os

def md(source): return {"cell_type":"markdown","metadata":{},"source":source}
def code(source, outputs=None): return {"cell_type":"code","execution_count":None,"metadata":{},"outputs":outputs or [],"source":source}

cells = []

# ─── TITLE ───
cells.append(md([
"# 🔬 AI Research Paper Analyzer — Complete Beginner's Guide\n",
"\n",
"> **Built with**: LangChain · Groq LLaMA 3.3-70B · FAISS · HuggingFace · Streamlit  \n",
"> **Supports**: PDF (text + scanned), JPG/JPEG/PNG (OCR), URLs, DOCX, CSV, TXT  \n",
"> **Skill Level**: Complete Beginner → Industry Professional\n",
"\n",
"---\n",
"\n",
"## 📚 What You Will Learn\n",
"This notebook explains the **complete architecture** of an industry-standard RAG pipeline for analyzing AI/ML research papers.  \n",
"By the end, you will understand:\n",
"- What RAG is and WHY it solves a real problem\n",
"- Every design decision made, with trade-off analysis\n",
"- How to extend this to a production system\n",
"\n",
"## 🗺️ Table of Contents\n",
"1. [The Problem RAG Solves](#1)\n",
"2. [What is RAG? Intuition First](#2)\n",
"3. [Architecture: Our Full Pipeline](#3)\n",
"4. [Tech Stack — Why Each Tool Was Chosen](#4)\n",
"5. [Document Loading: Multi-Format Support](#5)\n",
"6. [Text Chunking: The Critical Step](#6)\n",
"7. [Vector Embeddings: Teaching Machines to Read](#7)\n",
"8. [FAISS Vector Store: Lightning-Fast Search](#8)\n",
"9. [LLM Prompting for Research Papers](#9)\n",
"10. [Streamlit UI: Design Decisions](#10)\n",
"11. [Running the Application](#11)\n",
"12. [Trade-offs & Production Considerations](#12)\n",
]))

# ─── SECTION 1 ───
cells.append(md([
"---\n",
"<a id='1'></a>\n",
"# Section 1: The Problem RAG Solves 🤔\n",
"\n",
"## Why can't we just ask ChatGPT about a research paper?\n",
"\n",
"**Problem 1 — Knowledge Cutoff**  \n",
"LLMs like ChatGPT / LLaMA were trained on data up to a certain date. Papers published after training don't exist in the model's knowledge.\n",
"\n",
"**Problem 2 — Hallucination**  \n",
"When asked about specific papers, LLMs often *make up* plausible-sounding but wrong details: wrong numbers, wrong authors, wrong methods.\n",
"\n",
"**Problem 3 — Context Window Limits**  \n",
"Most research papers are 8,000–50,000+ characters. LLMs have token limits, and you can't just paste the whole paper.\n",
"\n",
"**Problem 4 — No Private Documents**  \n",
"Your internal lab reports, confidential papers, or pre-print drafts have never been seen by any LLM.\n",
"\n",
"## The RAG Solution ✅\n",
"\n",
"**Retrieval-Augmented Generation (RAG)** grounds the LLM in YOUR documents at runtime:  \n",
"1. The document is pre-processed and stored locally  \n",
"2. When you ask a question, RELEVANT chunks are retrieved  \n",
"3. Those chunks (not the whole document) are sent to the LLM as context  \n",
"4. The LLM answers based ONLY on what it was given — no hallucination about the paper\n",
]))

cells.append(code([
"# Illustration: The core RAG idea in pseudocode\n",
"\n",
"def traditional_llm(question):\n",
"    # LLM answers from its training data — may hallucinate\n",
"    return llm.generate(question)\n",
"\n",
"def rag_llm(question, document_chunks):\n",
"    # Step 1: Find the most relevant chunks\n",
"    relevant_chunks = vector_store.similarity_search(question, k=4)\n",
"    \n",
"    # Step 2: Build a prompt with real context\n",
"    prompt = f'''\n",
"    Answer based ONLY on this context from the paper:\n",
"    {relevant_chunks}\n",
"    \n",
"    Question: {question}\n",
"    '''\n",
"    \n",
"    # Step 3: LLM answers from real paper content — grounded!\n",
"    return llm.generate(prompt)\n",
"\n",
"print('RAG = Retrieval + Augmented + Generation')\n",
"print('Retrieval  -> Find relevant chunks from YOUR document')\n",
"print('Augmented  -> Augment the LLM prompt with those chunks')\n",
"print('Generation -> LLM generates answer from real context')\n",
]))

# ─── SECTION 2 ───
cells.append(md([
"---\n",
"<a id='2'></a>\n",
"# Section 2: What is RAG? The Bookshelf Analogy 📚\n",
"\n",
"## Think of it like an open-book exam\n",
"\n",
"| Scenario | Equivalent in RAG |\n",
"|----------|-------------------|\n",
"| The exam question | Your question to the system |\n",
"| The textbooks on your desk | The uploaded research paper |\n",
"| You flipping to relevant pages | Similarity search in FAISS |\n",
"| You reading those pages | LLM processing retrieved chunks |\n",
"| You writing the answer | LLM generating the response |\n",
"\n",
"## The Key Insight\n",
"> 🔑 **We never feed the whole paper to the LLM. We find the RELEVANT PARTS and feed only those.**\n",
"\n",
"This is exactly like how you wouldn't read an entire textbook to answer one question — you'd look at the index, find the right section, and read those few pages.\n",
"\n",
"## RAG vs Fine-Tuning: Which to Use?\n",
"\n",
"| Criteria | RAG (our approach) | Fine-Tuning |\n",
"|----------|-------------------|-------------|\n",
"| New documents | ✅ Works instantly | ❌ Need to retrain |\n",
"| Cost | ✅ Cheap (no GPU) | ❌ Very expensive |\n",
"| Accuracy | ✅ Uses exact text | ⚠️ May forget details |\n",
"| Private docs | ✅ Stays local | ❌ Needs upload to cloud |\n",
"| Speed to deploy | ✅ Minutes | ❌ Hours/days |\n",
"| **Verdict** | **Best for Q&A on docs** | **Best for behavior change** |\n",
"\n",
"**For a research paper Q&A system → RAG is the clear winner.**\n",
]))

# ─── SECTION 3 ───
cells.append(md([
"---\n",
"<a id='3'></a>\n",
"# Section 3: Architecture — Our Full Pipeline 🏗️\n",
"\n",
"```\n",
"┌─────────────────────────────────────────────────────────────────────┐\n",
"│                    INDEXING PHASE (runs once per document)          │\n",
"│                                                                     │\n",
"│  Document                                                           │\n",
"│  (PDF/Image/     →  Loader  →  Cleaner  →  Chunker  →  Embedder    │\n",
"│   URL/DOCX/CSV)                                                     │\n",
"│                                                    ↓                │\n",
"│                                              FAISS Index            │\n",
"│                                         (saved in memory)           │\n",
"└─────────────────────────────────────────────────────────────────────┘\n",
"\n",
"┌─────────────────────────────────────────────────────────────────────┐\n",
"│                    QUERY PHASE (runs on every question)             │\n",
"│                                                                     │\n",
"│  User Question  →  Embedder  →  FAISS Search  →  Top-K Chunks      │\n",
"│                                                         ↓           │\n",
"│                                              Prompt Template        │\n",
"│                                                         ↓           │\n",
"│                                              Groq LLaMA 3.3-70B    │\n",
"│                                                         ↓           │\n",
"│                                              Structured Answer      │\n",
"└─────────────────────────────────────────────────────────────────────┘\n",
"```\n",
"\n",
"## Components Summary\n",
"\n",
"| Component | Tool Used | Role |\n",
"|-----------|-----------|------|\n",
"| **Document Loader** | pypdf, pdfplumber, pytesseract, trafilatura | Extract raw text from any format |\n",
"| **Text Splitter** | LangChain RecursiveCharacterTextSplitter | Break text into overlapping chunks |\n",
"| **Embedder** | HuggingFace MiniLM-L6-v2 | Convert text to 384-dim vectors |\n",
"| **Vector Store** | FAISS (CPU) | Index & search vectors by similarity |\n",
"| **LLM** | Groq LLaMA 3.3-70B | Generate answers from retrieved context |\n",
"| **UI** | Streamlit | Web interface for upload, query, display |\n",
"| **Memory** | st.session_state | Keep chat history & vector store in RAM |\n",
]))

# ─── SECTION 4 ───
cells.append(md([
"---\n",
"<a id='4'></a>\n",
"# Section 4: Tech Stack — Why Each Tool Was Chosen 🛠️\n",
"\n",
"Every choice below was made after considering **cost, quality, speed, and ease of setup**.\n",
"\n",
"## 4.1 LLM: Groq + LLaMA 3.3 70B\n",
"\n",
"| Option | Quality | Cost | Speed | Why Not |\n",
"|--------|---------|------|-------|---------||\n",
"| **Groq LLaMA 3.3 70B** ✅ | ⭐⭐⭐⭐ | Free tier | Ultra-fast | — Our choice |\n",
"| OpenAI GPT-4o | ⭐⭐⭐⭐⭐ | Paid ($$$) | Fast | Cost |\n",
"| Ollama (local) | ⭐⭐⭐ | Free | Slow on CPU | Requires 16GB+ RAM |\n",
"| Google Gemini | ⭐⭐⭐⭐ | Free tier | Fast | API auth complexity |\n",
"\n",
"**Why LLaMA 3.3 70B on Groq?**  \n",
"- 70 billion parameters → understands complex academic language\n",
"- Groq's LPU hardware makes it 10–20× faster than GPU inference\n",
"- Free tier is very generous for personal/educational use\n",
"- `temperature=0.2` → deterministic, factual answers (not creative)\n",
"\n",
"## 4.2 Embeddings: HuggingFace MiniLM-L6-v2\n",
"\n",
"| Option | Quality | Cost | Speed | Dims |\n",
"|--------|---------|------|-------|------|\n",
"| **MiniLM-L6-v2** ✅ | ⭐⭐⭐ | Free (local) | Fast on CPU | 384 |\n",
"| OpenAI text-embedding-3-small | ⭐⭐⭐⭐⭐ | ~$0.02/1M tokens | API call | 1536 |\n",
"| OpenAI text-embedding-3-large | ⭐⭐⭐⭐⭐ | ~$0.13/1M tokens | API call | 3072 |\n",
"| BAAI/bge-large-en | ⭐⭐⭐⭐ | Free (local) | Slow on CPU | 1024 |\n",
"\n",
"**Why MiniLM-L6-v2?**  \n",
"- Runs fully locally → zero API cost, works offline, no data leaves your machine\n",
"- Surprisingly good quality for its size (6 transformer layers)\n",
"- Fast enough for interactive use on CPU\n",
"\n",
"## 4.3 Vector Store: FAISS\n",
"\n",
"| Option | Scale | Cost | Persistence | Why Not |\n",
"|--------|-------|------|-------------|---------||\n",
"| **FAISS (CPU)** ✅ | Up to ~100K docs | Free | In-memory | — Our choice |\n",
"| Pinecone | Millions of docs | Paid | Cloud | Overkill for single papers |\n",
"| Chroma | Up to ~10K docs | Free | Local file | Heavier setup |\n",
"| Weaviate | Enterprise-scale | Paid | Cloud | Too complex |\n",
"\n",
"**Why FAISS?**  \n",
"- Facebook AI Research's battle-tested library\n",
"- In-memory = sub-millisecond search on laptop hardware\n",
"- Perfect for single-document RAG sessions\n",
"\n",
"## 4.4 UI: Streamlit\n",
"\n",
"| Option | Learning Curve | Python-Native | Deployment |\n",
"|--------|---------------|---------------|------------|\n",
"| **Streamlit** ✅ | Minimal | Yes | Easy |\n",
"| Gradio | Minimal | Yes | Easy |\n",
"| FastAPI + React | High | No | Complex |\n",
"| Flask + Jinja | Medium | Partial | Medium |\n",
"\n",
"**Why Streamlit?**  \n",
"- Pure Python — no HTML/CSS required for functionality\n",
"- `st.session_state` handles stateful RAG chat natively\n",
"- `@st.cache_resource` caches embedding model across reruns\n",
"- Deploy to Streamlit Cloud in minutes\n",
]))

# ─── SECTION 5 ───
cells.append(md([
"---\n",
"<a id='5'></a>\n",
"# Section 5: Document Loading — Multi-Format Support 📥\n",
"\n",
"The hardest engineering challenge in this project is **handling messy real-world documents**.  \n",
"Research papers come in many forms:\n",
"- Clean text PDFs (most arxiv papers)\n",
"- Scanned PDFs (old papers, conference proceedings)\n",
"- Screenshots / photos of papers (JPG/JPEG/PNG)\n",
"- Web pages (arxiv abstract pages, blogs, documentation)\n",
"- Word documents, CSVs (supplementary materials)\n",
"\n",
"## 5.1 PDF Loading Strategy: Three-Pass Fallback\n",
"\n",
"```\n",
"Pass 1: pypdf       → Fast, handles most modern PDFs\n",
"   ↓ (if < 500 chars extracted)\n",
"Pass 2: pdfplumber  → Better layout extraction for dense tables/columns  \n",
"   ↓ (if still < 300 chars)\n",
"Pass 3: OCR         → pdf2image converts pages to images → Tesseract reads them\n",
"```\n",
"\n",
"This graceful degradation ensures we always get text if it's humanly readable.\n",
]))

cells.append(code([
"# The PDF loading logic (simplified from app.py)\n",
"import io\n",
"\n",
"def load_pdf_demo(file_path: str) -> str:\n",
"    \"\"\"\n",
"    Three-pass PDF text extraction with graceful fallback.\n",
"    \"\"\"\n",
"    with open(file_path, 'rb') as f:\n",
"        file_bytes = f.read()\n",
"    \n",
"    # ── PASS 1: pypdf (fast, handles text-layer PDFs) ──\n",
"    text = ''\n",
"    try:\n",
"        from pypdf import PdfReader\n",
"        reader = PdfReader(io.BytesIO(file_bytes))\n",
"        for page in reader.pages:\n",
"            text += (page.extract_text() or '') + '\\n'\n",
"        print(f'Pass 1 (pypdf): {len(text)} characters extracted')\n",
"    except Exception as e:\n",
"        print(f'Pass 1 failed: {e}')\n",
"\n",
"    # ── PASS 2: pdfplumber (if pypdf got too little) ──\n",
"    if len(text.strip()) < 500:\n",
"        try:\n",
"            import pdfplumber\n",
"            with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:\n",
"                text = ''.join(p.extract_text() or '' for p in pdf.pages)\n",
"            print(f'Pass 2 (pdfplumber): {len(text)} characters extracted')\n",
"        except ImportError:\n",
"            print('pdfplumber not installed, skipping Pass 2')\n",
"\n",
"    # ── PASS 3: OCR (for scanned PDFs) ──\n",
"    if len(text.strip()) < 300:\n",
"        print('Falling back to OCR (pdf2image + pytesseract)...')\n",
"        try:\n",
"            from pdf2image import convert_from_bytes\n",
"            import pytesseract\n",
"            images = convert_from_bytes(file_bytes, dpi=200)\n",
"            text = '\\n\\n'.join(pytesseract.image_to_string(img) for img in images)\n",
"            print(f'Pass 3 (OCR): {len(text)} characters extracted')\n",
"        except Exception as e:\n",
"            print(f'OCR failed: {e}')\n",
"\n",
"    return text\n",
"\n",
"print('PDF loading strategy: pypdf → pdfplumber → OCR')\n",
"print('This ensures maximum text extraction for any PDF type.')\n",
]))

cells.append(md([
"## 5.2 Image OCR Pipeline (JPG/JPEG/PNG)\n",
"\n",
"```\n",
"Image File\n",
"    ↓\n",
"Pillow (PIL) → Convert to RGB, upscale if small (< 1000px wide)\n",
"    ↓\n",
"Tesseract OCR Engine → Extract text character by character\n",
"    ↓\n",
"Raw text string ready for chunking\n",
"```\n",
"\n",
"**Why upscale images?**  \n",
"Tesseract performs significantly better on larger images. A 300px-wide image may give 60% accuracy; at 1000px+ it reaches 95%+.\n",
"\n",
"## 5.3 URL Scraping: Two-Pass Strategy\n",
"\n",
"```\n",
"Pass 1: trafilatura  → Best for articles/papers (removes nav, ads, footers)\n",
"   ↓ (if < 300 chars or blocked)\n",
"Pass 2: LangChain WebBaseLoader → General HTML scraping with BeautifulSoup\n",
"```\n",
"\n",
"**trafilatura** is used by academic publishers and news agencies — it's specifically  \n",
"designed to extract the MAIN CONTENT of a page, not navigation or ads.\n",
]))

# ─── SECTION 6 ───
cells.append(md([
"---\n",
"<a id='6'></a>\n",
"# Section 6: Text Chunking — The Critical Step ✂️\n",
"\n",
"## Why do we chunk at all?\n",
"\n",
"1. **Token limits**: LLMs have a maximum input size (context window). We can't send 50,000 chars at once.\n",
"2. **Precision**: Sending only the RELEVANT chunks means the LLM focuses on what matters.\n",
"3. **Search accuracy**: Smaller chunks = more precise similarity search.\n",
"\n",
"## Chunking Parameters We Use\n",
"\n",
"```python\n",
"chunk_size    = 1000   # characters per chunk\n",
"chunk_overlap = 200    # overlap between adjacent chunks\n",
"```\n",
"\n",
"## Why 1000 chars / 200 overlap?\n",
"\n",
"| Chunk Size | Too Small (<500) | Optimal (1000) | Too Large (>3000) |\n",
"|------------|-----------------|----------------|-------------------|\n",
"| Context | ❌ Context lost | ✅ Good context | ❌ Too much noise |\n",
"| Search precision | ✅ Very precise | ✅ Precise | ❌ Imprecise |\n",
"| # Chunks created | ❌ Too many | ✅ Manageable | ✅ Fewer |\n",
"| Token efficiency | ✅ Cheap | ✅ Balanced | ❌ Expensive |\n",
"\n",
"**1000 chars ≈ ~250 tokens** — fits 8–12 relevant chunks in a 4096-token context window.\n",
"\n",
"## Why Overlap?\n",
"\n",
"Without overlap, a sentence split across two chunks would lose meaning:\n",
"```\n",
"Chunk 1: '...The transformer uses multi-head attention to'\n",
"Chunk 2: 'capture long-range dependencies in the sequence...'\n",
"```\n",
"With 200-char overlap, BOTH chunks contain the full concept.\n",
"\n",
"## RecursiveCharacterTextSplitter: Split Order\n",
"\n",
"The splitter tries to split at these separators in order (most preferred first):\n",
"```\n",
"['\\n\\n', '\\n', '. ', '! ', '? ', ' ', '']\n",
"```\n",
"This means: try to split at paragraph breaks first, then sentences, then words, as a last resort character-by-character. This maximizes semantic coherence of each chunk.\n",
]))

cells.append(code([
"# Chunking demonstration (no API key needed)\n",
"from langchain_text_splitters import RecursiveCharacterTextSplitter\n",
"\n",
"sample_text = '''\n",
"Abstract: We propose a novel transformer architecture called ResearchNet that achieves\n",
"state-of-the-art performance on five NLP benchmarks. Our method introduces sparse\n",
"cross-attention layers that reduce computational complexity from O(n^2) to O(n log n)\n",
"while maintaining accuracy.\n",
"\n",
"1. Introduction\n",
"The rapid advancement of large language models has revolutionized natural language\n",
"processing. However, scaling these models requires quadratic memory and compute with\n",
"respect to sequence length. This limitation prevents application to long documents.\n",
"\n",
"2. Methodology\n",
"Our approach uses a sparse attention pattern where each token attends to its k\n",
"nearest neighbors plus a set of global tokens. This preserves local context while\n",
"maintaining global information flow through the network.\n",
"'''\n",
"\n",
"splitter = RecursiveCharacterTextSplitter(\n",
"    chunk_size=300,       # small for demo clarity\n",
"    chunk_overlap=50,\n",
"    separators=['\\n\\n', '\\n', '. ', ' ', ''],\n",
")\n",
"\n",
"chunks = splitter.split_text(sample_text)\n",
"\n",
"print(f'Original text: {len(sample_text)} chars')\n",
"print(f'Number of chunks: {len(chunks)}')\n",
"print('=' * 60)\n",
"for i, chunk in enumerate(chunks, 1):\n",
"    print(f'-- Chunk {i} ({len(chunk)} chars) --')\n",
"    print(chunk.strip())\n",
"    print()\n",
]))

# ─── SECTION 7 ───
cells.append(md([
"---\n",
"<a id='7'></a>\n",
"# Section 7: Vector Embeddings — Teaching Machines to Read 🧠\n",
"\n",
"## What is an embedding?\n",
"\n",
"An embedding converts text into a list of numbers (a **vector**) that captures semantic meaning.\n",
"Similar sentences → similar vectors → close together in space.\n",
"\n",
"```\n",
"'self-attention mechanism'  →  [0.12, -0.43, 0.89, ..., 0.23]  (384 numbers)\n",
"'multi-head attention layer' →  [0.11, -0.41, 0.87, ..., 0.25]  ← very similar!\n",
"'cats eat fish'              →  [-0.78, 0.22, -0.13, ..., 0.56]  ← very different\n",
"```\n",
"\n",
"## How Similarity Search Works\n",
"\n",
"When you ask a question:\n",
"1. Your question is embedded into a vector\n",
"2. FAISS finds the k vectors CLOSEST to your question vector (cosine similarity)\n",
"3. Those chunks are returned as context\n",
"\n",
"This works because: **semantically similar text → geometrically close vectors**\n",
"\n",
"## MiniLM-L6-v2: Our Model\n",
"\n",
"- **MiniLM**: Microsoft's compressed BERT variant — 40MB vs BERT's 440MB\n",
"- **L6**: 6 transformer layers (BERT has 12)\n",
"- **v2**: Second version, fine-tuned on 1B sentence pairs for semantic similarity\n",
"- **Output**: 384-dimensional vectors (directions in 384D space)\n",
"- **Normalization**: `normalize_embeddings=True` → cosine similarity = dot product\n",
]))

cells.append(code([
"# Embedding demonstration (requires: pip install sentence-transformers)\n",
"import numpy as np\n",
"\n",
"try:\n",
"    from sentence_transformers import SentenceTransformer\n",
"    \n",
"    model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')\n",
"    \n",
"    sentences = [\n",
"        'self-attention mechanism in transformers',\n",
"        'multi-head attention allows parallel attention computation',\n",
"        'the cat sat on the mat',\n",
"        'gradient descent optimization',\n",
"    ]\n",
"    \n",
"    embeddings = model.encode(sentences, normalize_embeddings=True)\n",
"    \n",
"    print(f'Embedding shape: {embeddings.shape}')  # (4, 384)\n",
"    print(f'Each sentence → {embeddings.shape[1]}-dimensional vector\\n')\n",
"    \n",
"    # Cosine similarity (dot product of normalized vectors)\n",
"    print('Cosine Similarity Matrix (1.0 = identical, 0.0 = unrelated):')\n",
"    print('-' * 65)\n",
"    sim_matrix = embeddings @ embeddings.T\n",
"    \n",
"    for i, s1 in enumerate(sentences):\n",
"        for j, s2 in enumerate(sentences):\n",
"            if j > i:\n",
"                sim = sim_matrix[i, j]\n",
"                bar = '█' * int(sim * 20)\n",
"                print(f's{i+1} vs s{j+1}: {sim:.3f} {bar}')\n",
"    \n",
"    print('\\nKey insight: s1 and s2 (both about attention) are much more similar')\n",
"    print('than s1 and s3 (attention vs cat), validating semantic search works!')\n",
"\n",
"except ImportError:\n",
"    print('Run: pip install sentence-transformers')\n",
"    print('This will demonstrate why semantic search works.')\n",
]))

# ─── SECTION 8 ───
cells.append(md([
"---\n",
"<a id='8'></a>\n",
"# Section 8: FAISS Vector Store — Lightning-Fast Search ⚡\n",
"\n",
"## What is FAISS?\n",
"\n",
"FAISS (Facebook AI Similarity Search) is a C++ library (with Python bindings) that:\n",
"- Stores millions of high-dimensional vectors efficiently\n",
"- Finds the k nearest neighbors in milliseconds\n",
"- Runs on CPU or GPU\n",
"- Used in production by Meta, Google, Spotify, etc.\n",
"\n",
"## How it works in our pipeline\n",
"\n",
"```python\n",
"# Creating the index\n",
"vectorstore = FAISS.from_documents(chunks, embeddings)\n",
"# Internally: each chunk → embedding vector → stored in FAISS index\n",
"\n",
"# Searching\n",
"results = vectorstore.similarity_search('what is self-attention?', k=4)\n",
"# Internally: question → embedding → nearest 4 chunk vectors → return chunks\n",
"```\n",
"\n",
"## FAISS vs Alternatives\n",
"\n",
"| Store | Persistence | Scale | Setup | Best For |\n",
"|-------|-------------|-------|-------|----------|\n",
"| **FAISS** ✅ | RAM/local file | Up to ~100K | `pip install faiss-cpu` | Single-session RAG |\n",
"| ChromaDB | SQLite local | ~10K-100K | Medium | Multi-session apps |\n",
"| Pinecone | Cloud | Millions | Account + API | Production SaaS |\n",
"| Weaviate | Docker/Cloud | Millions | Complex | Enterprise |\n",
"\n",
"## Why we use in-memory FAISS (no save_local)\n",
"\n",
"In our app, the vector store lives in `st.session_state`:  \n",
"✅ Instant access, no disk I/O  \n",
"✅ Document hash check avoids rebuilding for same file  \n",
"✅ Cleared automatically when user resets or closes browser  \n",
"✅ No privacy risk — nothing written to disk permanently  \n",
]))

cells.append(code([
"# FAISS demonstration (no API key needed)\n",
"import numpy as np\n",
"\n",
"try:\n",
"    import faiss\n",
"    \n",
"    # Simulate 10 document chunks as 384-dim random vectors\n",
"    np.random.seed(42)\n",
"    dimension = 384\n",
"    n_chunks = 10\n",
"    \n",
"    chunk_vectors = np.random.randn(n_chunks, dimension).astype('float32')\n",
"    # Normalize (cosine similarity)\n",
"    chunk_vectors = chunk_vectors / np.linalg.norm(chunk_vectors, axis=1, keepdims=True)\n",
"    \n",
"    # Build FAISS index\n",
"    index = faiss.IndexFlatIP(dimension)  # Inner Product = cosine similarity (for normalized vecs)\n",
"    index.add(chunk_vectors)\n",
"    \n",
"    print(f'Index built with {index.ntotal} vectors of dimension {dimension}')\n",
"    \n",
"    # Simulate a query\n",
"    query = np.random.randn(1, dimension).astype('float32')\n",
"    query = query / np.linalg.norm(query)\n",
"    \n",
"    # Search for top-4 similar chunks\n",
"    k = 4\n",
"    distances, indices = index.search(query, k)\n",
"    \n",
"    print(f'\\nTop {k} most similar chunks to query:')\n",
"    for rank, (dist, idx) in enumerate(zip(distances[0], indices[0]), 1):\n",
"        print(f'  Rank {rank}: Chunk #{idx:2d} | Cosine similarity = {dist:.4f}')\n",
"    \n",
"    print('\\nThis is exactly what happens when you ask a question:')\n",
"    print('Your question vector → nearest chunk vectors → retrieve those chunks')\n",
"\n",
"except ImportError:\n",
"    print('FAISS demo requires: pip install faiss-cpu')\n",
"    print('But this is already in requirements.txt!')\n",
]))

# ─── SECTION 9 ───
cells.append(md([
"---\n",
"<a id='9'></a>\n",
"# Section 9: LLM Prompting for Research Papers 🎯\n",
"\n",
"## The Art of Prompt Engineering\n",
"\n",
"**Prompt engineering** is how we get consistent, structured, high-quality output from LLMs.  \n",
"For research papers, vague prompts give vague answers. We need structured prompts.\n",
"\n",
"## Our 4 Prompt Templates\n",
"\n",
"### Template 1: Structured Summary\n",
"Retrieves chunks from 5 targeted queries (problem, method, results, contributions, limitations)  \n",
"→ Forces LLM to fill a **6-section structured template**  \n",
"→ If info not in context, says so honestly (no hallucination)\n",
"\n",
"### Template 2: Chat Q&A\n",
"- Includes last 4 turns of conversation history (prevents context overflow)\n",
"- Strictly anchored to retrieved context only\n",
"- Provides a graceful 'not found' response instead of hallucinating\n",
"\n",
"### Template 3: Quick Insights\n",
"- Forces exactly 5 bullet points with a one-line takeaway\n",
"- Consistent output format every time\n",
"\n",
"### Template 4: Section Deep-Dive\n",
"- User specifies a section (e.g., 'ablation study')\n",
"- 5-part structured response: Overview, Technical Details, Significance, Connections, Key Terms\n",
"\n",
"## Key Prompt Engineering Principles Used\n",
"\n",
"| Principle | Implementation in our prompts |\n",
"|-----------|-------------------------------|\n",
"| **Grounding** | 'Answer ONLY from the provided context' |\n",
"| **Honesty** | 'If not in context, say so explicitly' |\n",
"| **Structure** | Exact template with `##` headers forces consistent output |\n",
"| **Role** | 'You are an expert AI/ML research paper analyst' |\n",
"| **Temperature** | 0.2 = factual mode (not creative) |\n",
"| **Max tokens** | 3000 = enough for structured summaries without API cost spike |\n",
]))

cells.append(code([
"# Prompt template demonstration\n",
"\n",
"STRUCTURED_SUMMARY_PROMPT = '''\n",
"You are an expert AI/ML research paper analyst. Analyze the provided context\n",
"from a research paper and produce a STRUCTURED summary.\n",
"\n",
"Context from the paper:\n",
"{context}\n",
"\n",
"Produce this exact structure:\n",
"\n",
"## Problem Statement\n",
"[What problem does this paper solve?]\n",
"\n",
"## Key Contributions\n",
"[List 3-5 specific novel contributions]\n",
"\n",
"## Methodology\n",
"[Explain the method with technical details]\n",
"\n",
"## Results\n",
"[Quantitative results, benchmarks, comparisons]\n",
"\n",
"## Limitations\n",
"[Acknowledged or apparent limitations]\n",
"\n",
"## Future Work\n",
"[Directions suggested by authors]\n",
"\n",
"If any section is NOT in the context, write: '[Not found in provided excerpt]'\n",
"NEVER make up information not present in the context.\n",
"'''\n",
"\n",
"# Key design decisions in this prompt:\n",
"print('PROMPT DESIGN DECISIONS:')\n",
"print('1. Role: Expert analyst → activates specialized knowledge')\n",
"print('2. Context first: prevents the LLM from using training data')\n",
"print('3. Exact structure: ## headers force consistent markdown output')\n",
"print('4. Explicit fallback: prevents hallucination on missing sections')\n",
"print('5. NEVER make up: explicit prohibition reinforces grounding')\n",
"print()\n",
"print('This prompt is used with k=12 retrieved chunks (broader coverage)')\n",
"print('vs Chat which uses k=4 (more precise, faster)')\n",
]))

# ─── SECTION 10 ───
cells.append(md([
"---\n",
"<a id='10'></a>\n",
"# Section 10: Streamlit UI — Design Decisions 🎨\n",
"\n",
"## Key Streamlit Concepts Used\n",
"\n",
"### `st.session_state` — The Memory of RAG\n",
"Without `st.session_state`, Streamlit reruns the entire script on every interaction.  \n",
"We use it to persist:\n",
"- `vector_store` — the FAISS index (expensive to rebuild)\n",
"- `doc_hash` — SHA-256 fingerprint of the document (prevents reprocessing)\n",
"- `chat_history` — conversation turns for multi-turn chat\n",
"- `raw_text` — the extracted document text\n",
"\n",
"### `@st.cache_resource` — Cache the Embedding Model\n",
"Loading MiniLM-L6-v2 takes ~3 seconds on first run.  \n",
"`@st.cache_resource` caches the model object in memory and reuses it across reruns.  \n",
"This is different from `@st.cache_data` which is for serializable objects (lists, dicts, DataFrames).\n",
"\n",
"### Document Hash Check\n",
"```python\n",
"current_hash = hashlib.sha256(file_bytes).hexdigest()\n",
"if current_hash == st.session_state.doc_hash:\n",
"    return True  # Skip reprocessing\n",
"```\n",
"This ensures that if you upload the same PDF twice (or rerun the app), it uses the cached vector store.\n",
"\n",
"### Dark Theme via Custom CSS\n",
"Streamlit's built-in themes are limited. We inject custom HTML/CSS with `st.markdown(html, unsafe_allow_html=True)` to achieve:\n",
"- Dark gradient backgrounds (`#0d1117`, GitHub dark theme)\n",
"- Blue gradient text for headers\n",
"- Custom chat bubbles, badge components, and metric boxes\n",
"- Google Fonts (Inter) for professional typography\n",
"\n",
"## Tab Layout: 4 Analysis Modes\n",
"```\n",
"Tab 1: Structured Summary — One-click full paper breakdown (7 sections)\n",
"Tab 2: Chat Q&A          — Multi-turn conversation with history\n",
"Tab 3: Quick Insights    — 5 bullet points for rapid overview  \n",
"Tab 4: Section Deep-Dive — Focus on specific section or concept\n",
"```\n",
"This avoids a single cluttered page and allows users to switch between modes fluidly.\n",
]))

# ─── SECTION 11 ───
cells.append(md([
"---\n",
"<a id='11'></a>\n",
"# Section 11: Running the Application 🚀\n",
"\n",
"## Prerequisites\n",
"\n",
"### 1. Environment Setup\n",
"```bash\n",
"# Navigate to project folder\n",
"cd path/to/Rag_final\n",
"\n",
"# Activate virtual environment (Windows)\n",
"venv\\Scripts\\activate\n",
"\n",
"# Install all dependencies\n",
"pip install -r requirements.txt\n",
"```\n",
"\n",
"### 2. Optional: Tesseract for Image OCR\n",
"For JPG/JPEG/PNG and scanned PDF support:  \n",
"- **Windows**: Download installer from https://github.com/UB-Mannheim/tesseract/wiki  \n",
"- **Ubuntu**: `sudo apt-get install tesseract-ocr`  \n",
"- **macOS**: `brew install tesseract`\n",
"\n",
"### 3. API Key\n",
"Already in `.env`: `GROQ_API_KEY=gsk_...`  \n",
"Or get a free key at https://console.groq.com/keys\n",
"\n",
"### 4. Launch\n",
"```bash\n",
"# The key command — MUST use streamlit run, not python app.py\n",
"streamlit run app.py\n",
"```\n",
"Opens at: **http://localhost:8501**\n",
"\n",
"## Workflow in the App\n",
"\n",
"```\n",
"1. Sidebar → Select input type (PDF/Image/URL/etc.)\n",
"2. Sidebar → Upload file or paste URL\n",
"3. Sidebar → Click '🚀 Analyze Document'\n",
"4. Main area → Wait for 4-step progress bar (Load → Chunk → Embed → Index)\n",
"5. Main area → Use any of the 4 analysis tabs:\n",
"   • Tab 1: Click 'Generate Summary' for full structured breakdown\n",
"   • Tab 2: Type questions, click 'Ask' — conversation builds up\n",
"   • Tab 3: Click 'Generate Insights' for 5-bullet summary\n",
"   • Tab 4: Type a section name, click 'Deep Dive'\n",
"6. Download summary as Markdown (Tab 1)\n",
"7. Reset with sidebar '🗑️ Clear & Reset' button\n",
"```\n",
"\n",
"## File Structure\n",
"```\n",
"Rag_final/\n",
"├── app.py                        ← Main application (run this with streamlit)\n",
"├── requirements.txt              ← All dependencies\n",
"├── .env                         ← API keys (never commit this!)\n",
"├── .gitignore                   ← Excludes venv, .env, __pycache__\n",
"├── research_paper_analyzer.ipynb ← This tutorial notebook\n",
"├── pdfchat.py                   ← Original basic PDF QA (kept for reference)\n",
"├── url.py                       ← Original URL QA (kept for reference)\n",
"└── venv/                        ← Virtual environment (never commit)\n",
"```\n",
]))

# ─── SECTION 12 ───
cells.append(md([
"---\n",
"<a id='12'></a>\n",
"# Section 12: Trade-offs & Production Considerations 🏭\n",
"\n",
"## Current Limitations (Honest Assessment)\n",
"\n",
"| Limitation | Impact | Production Solution |\n",
"|------------|--------|--------------------|\n",
"| FAISS is in-memory | Lost on browser close | Use ChromaDB with SQLite persistence |\n",
"| Single document per session | Can't compare papers | Multi-doc FAISS index with metadata filters |\n",
"| MiniLM-L6-v2 quality | Lower than OpenAI embeddings | Upgrade to `text-embedding-3-small` for critical use |\n",
"| Groq free tier rate limits | Throttled on heavy use | Upgrade plan or add OpenAI fallback |\n",
"| OCR quality varies | Poor on handwritten text | Use Google Vision API or Azure Form Recognizer |\n",
"| No authentication | Anyone can use your API key | Add Streamlit auth or use secrets management |\n",
"\n",
"## What Makes This 'Industry Standard'\n",
"\n",
"✅ **Graceful degradation**: 3-pass PDF loading, 2-pass URL scraping  \n",
"✅ **Cache intelligence**: SHA-256 document hash check avoids reprocessing  \n",
"✅ **Metadata injection**: Every chunk carries source, page, index → citation-aware  \n",
"✅ **Session state**: Proper Streamlit state management for multi-turn chat  \n",
"✅ **Error handling**: Specific, actionable error messages for every failure mode  \n",
"✅ **Modular design**: Each pipeline stage (load/chunk/embed/retrieve/generate) is a separate function  \n",
"✅ **Temperature tuning**: 0.2 for factual tasks, not 0.0 (too rigid) or 0.7 (too creative)  \n",
"✅ **Chunk overlap**: 200-char overlap prevents context loss at boundaries  \n",
"\n",
"## Scaling to Production\n",
"\n",
"```\n",
"Current (Personal/Lab)          Production SaaS\n",
"──────────────────────          ──────────────────────────────────\n",
"FAISS in-memory              →  Pinecone / Weaviate (cloud vector DB)\n",
"Single user session          →  PostgreSQL user accounts + doc library\n",
"Groq free tier               →  OpenAI + fallback LLM routing\n",
"Local MiniLM embeddings      →  OpenAI text-embedding-3-small\n",
"Streamlit Community Cloud    →  AWS ECS / GCP Cloud Run + Docker\n",
"No auth                      →  Auth0 / Firebase Auth\n",
"Single PDF                   →  Multi-doc comparison + semantic search\n",
"```\n",
"\n",
"## The RAG Quality Triangle\n",
"\n",
"```\n",
"          ACCURACY\n",
"             △\n",
"            /|\\\n",
"           / | \\\n",
"          /  |  \\\n",
"         /   |   \\\n",
"  SPEED ◁────┼────▷ COST\n",
"```\n",
"\n",
"Our setup optimizes for **Speed + Cost** (free, fast)  \n",
"At the mild expense of **Accuracy** (MiniLM vs OpenAI embeddings)  \n",
"For research/education → this trade-off is exactly right.\n",
"\n",
"---\n",
"\n",
"## 🎉 Congratulations!\n",
"\n",
"You now understand the complete architecture of an industry-standard RAG system:  \n",
"\n",
"| Concept | You Learned |\n",
"|---------|-------------|\n",
"| **Why RAG** | Grounds LLMs in your documents, eliminates hallucination |\n",
"| **Document Loading** | Multi-format with graceful 3-pass fallback |\n",
"| **Chunking** | 1000 chars / 200 overlap — the optimal research paper balance |\n",
"| **Embeddings** | Text → 384-dim vectors via MiniLM-L6-v2 |\n",
"| **FAISS** | Millisecond k-nearest-neighbor search over all chunks |\n",
"| **Prompting** | Structured, grounded, honest templates for 4 analysis modes |\n",
"| **Streamlit** | session_state, cache_resource, custom CSS for professional UI |\n",
"| **Trade-offs** | Cost vs quality, local vs cloud, speed vs accuracy |\n",
"\n",
"Run the app with: **`streamlit run app.py`**\n",
]))

# ─── BUILD NOTEBOOK ───
nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11.0"},
    },
    "cells": cells,
}

out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "research_paper_analyzer.ipynb")
with open(out_path, "w", encoding="utf-8", errors="replace") as f:
    json.dump(nb, f, indent=1, ensure_ascii=True)

print(f"✅ Notebook created: {out_path}")
print(f"   Cells: {len(cells)}")
print("Run: jupyter notebook research_paper_analyzer.ipynb")
